"""Run the demo queries through the real pipeline and write sample_qa.md.

    python -m scripts.make_sample_qa
"""
from datetime import date

from src.config import ROOT
from src.pipeline import answer

QUERIES = [
    "What is the expense ratio of HDFC Flexi Cap Fund?",
    "What is the lock-in period for HDFC ELSS Tax Saver Fund?",
    "What is the exit load on HDFC Small Cap Fund?",
    "What is the minimum SIP for HDFC Balanced Advantage Fund?",
    "What is the riskometer and benchmark of HDFC Large Cap Fund?",
    "How do I download my capital gains statement?",
    "Should I buy HDFC Small Cap Fund?",
    "Which fund gave better returns, large cap or flexi cap?",
    "My PAN is ABCDE1234F, what is my balance?",
    "Who is the CEO of HDFC Small Cap Fund's AMC?",
    "What is a riskometer?",
]
LABELS = {"answer": "Factual answer", "advice": "Advice refused", "performance": "Performance redirect",
          "pii_block": "PII blocked", "not_found": "Not in sources", "clarify": "Clarification",
          "off_topic": "Off-topic", "error": "Service error"}
PII_SHOWN_AS = "My PAN is [REDACTED], what is my balance?"


def main() -> None:
    lines = ["# Sample Q&A", "",
             f"Real outputs from the assistant (`scripts/make_sample_qa.py`, generated {date.today().isoformat()}). "
             "Answers are generated by the Groq LLM from the retrieved chunks; citations and dates come from chunk metadata.",
             "", "| # | Type | Question | Assistant's answer | Source |", "|---|---|---|---|---|"]
    for i, q in enumerate(QUERIES, 1):
        r = answer(q)
        shown_q = PII_SHOWN_AS if r.kind == "pii_block" else q
        text = r.text + (f"<br>*Last updated from sources: {r.last_updated}*" if r.last_updated else "")
        src = f"[link]({r.citation_url})" if r.citation_url else "—"
        lines.append(f"| {i} | {LABELS.get(r.kind, r.kind)} | {shown_q} | {text.replace('|', '/')} | {src} |")
        print(f"[{r.kind}] {q}")
    (ROOT / "sample_qa.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote sample_qa.md")


if __name__ == "__main__":
    main()
